//! Rendering a [`Grade`] into the two output formats: the human-readable
//! GRADE.md report and the `--json` machine format. Both reproduce the original
//! implementation's layout exactly (including blank lines and field order).

use crate::fmt::{json_number, to_fixed};
use crate::scoring::{Grade, Scored};
use serde_json::json;

/// Build the GRADE.md body (without the trailing newline the file adds).
pub fn markdown(grade: &Grade, project_label: &str, src_files: usize, test_files: usize) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push(format!("# Grade Report — {}", grade.course.to_uppercase()));
    lines.push(String::new());
    lines.push(format!(
        "**Grade: {}  ({} / 100)**",
        grade.grade,
        to_fixed(grade.pct, 1)
    ));
    lines.push(String::new());
    lines.push(format!(
        "Project: `{}` · {} · {} source file(s), {} test file(s) · generated by `git-cs-grade`.",
        project_label, grade.lang, src_files, test_files
    ));
    lines.push(String::new());
    lines.push(
        "> Structural rubric: grades design, abstraction, tests, documentation, style, and".into(),
    );
    lines.push(
        "> cleanliness — the things you can restructure. It does **not** run the course".into(),
    );
    lines.push("> autograder's correctness suite; pair it with the official tests.".into());
    lines.push(String::new());
    lines.push("## Scorecard".into());
    lines.push(String::new());
    lines.push("| Category | Score | Weight | Evidence |".into());
    lines.push("| -------- | ----- | ------ | -------- |".into());
    for r in &grade.results {
        lines.push(format!(
            "| {} | {} | {} | {} |",
            r.name,
            to_fixed(r.earned, 1),
            r.weight,
            r.evidence
        ));
    }
    lines.push(format!(
        "| **Total** | **{}** | **100** | **{}** |",
        to_fixed(grade.pct, 1),
        grade.grade
    ));
    lines.push(String::new());

    if grade.gaps.is_empty() {
        lines.push("## Path to A+".into());
        lines.push(String::new());
        lines.push(
            "🎉 Already at A+ on this structural rubric. Confirm correctness with the course autograder."
                .into(),
        );
    } else {
        lines.push("## Path to A+ (highest-impact first)".into());
        lines.push(String::new());
        for g in &grade.gaps {
            lines.push(format!(
                "### {}  — recover up to {} pts",
                g.scored.name,
                to_fixed(g.recoverable, 1)
            ));
            for fix in &g.scored.fixes {
                lines.push(format!("- [ ] {fix}"));
            }
            if g.scored.fixes.is_empty() {
                lines.push(format!(
                    "- [ ] Polish \"{}\" — close the remaining gap to full marks.",
                    g.scored.name
                ));
            }
            lines.push(String::new());
        }
        lines.push(
            "After applying fixes, re-run `git-cs-grade` (or `helpers grade`) and repeat until the grade is A+."
                .into(),
        );
    }
    lines.push(String::new());
    lines.join("\n")
}

/// Build the `--json` payload, matching the original field order and number
/// formatting (`JSON.stringify(..., null, 2)`).
pub fn json(grade: &Grade) -> String {
    let results: Vec<serde_json::Value> = grade.results.iter().map(scored_to_json).collect();
    let gaps: Vec<serde_json::Value> = grade
        .gaps
        .iter()
        .map(|g| {
            let mut obj = scored_to_json(&g.scored);
            obj.as_object_mut()
                .unwrap()
                .insert("recoverable".into(), json_number(g.recoverable));
            obj
        })
        .collect();

    let payload = json!({
        "course": grade.course,
        "lang": grade.lang,
        "pct": json_number(grade.pct),
        "grade": grade.grade,
        "total": json_number(grade.total),
        "results": results,
        "gaps": gaps,
    });
    serde_json::to_string_pretty(&payload).expect("serialize grade")
}

fn scored_to_json(r: &Scored) -> serde_json::Value {
    json!({
        "name": r.name,
        "weight": r.weight,
        "earned": json_number(r.earned),
        "score": json_number(r.score),
        "evidence": r.evidence,
        "fixes": r.fixes,
    })
}
