//! MCP tools for sharing and tuning the linter's learned knowledge.
//!
//! Languages self-train: the lint run itself crawls official docs for any language it sees and
//! caches the model (near-instant reuse after first setup). These tools cover the human loop:
//!
//! * `lint_submit` — commit trained models + corpus, push, and open a GitHub PR (share knowledge).
//! * `lint_rule`   — author/promote a project rule (including feedback drafts) into `.helpers/lint-rules/`.
//! * `lint_config` — per-project ignores/severity overrides (rarely needed; feedback flags manage this).

use serde_json::{json, Value};

use crate::proto::{text, ToolResult};

// ── lint_submit ───────────────────────────────────────────────────────────────

/// Commit newly-trained models + corpus changes and open a GitHub PR so others get them.
/// `models=true` instead publishes this machine's learned catalogs to the GitHub model
/// registry (the `lint-models` branch of origin) so other machines download instead of
/// re-crawling (LINTER.md, "No connectivity flags").
pub fn run_submit(args: &Value) -> ToolResult {
    if args["identity"].as_bool().unwrap_or(false) {
        return Ok(vec![text(format!(
            "This machine's signing identity (Ed25519 public key): {}\nPrivate key: ~/.config/helpers/signing.key — never leaves this machine.",
            crate::lint_sign::machine_fingerprint()?
        ))]);
    }
    if args["models"].as_bool().unwrap_or(false) {
        return Ok(vec![text(publish_models(&crate::git::workspace_root())?)]);
    }
    let desc = args["description"]
        .as_str()
        .unwrap_or("Add trained language models from official docs");
    let data_root = crate::tools::lint::data_root_pub();
    let repo_root = crate::git::workspace_root();

    let mut paths: Vec<std::path::PathBuf> = ["lint-index/sources.json", "corpus"]
        .iter()
        .map(|p| data_root.join(p))
        .filter(|p| p.exists())
        .collect();

    // Opt-in: also share the project's lint feedback log so false-positive/missed flags can
    // improve the shared rules. Off by default because feedback may reference private file paths.
    if args["include_feedback"].as_bool().unwrap_or(false) {
        let fb = crate::lint_feedback::feedback_path(&repo_root);
        if fb.exists() {
            paths.push(fb);
        }
    }

    if paths.is_empty() {
        return Err("lint_submit: nothing to submit — no sources, corpus, or feedback changes found".into());
    }

    let result = commit_and_pr(&repo_root, &paths, desc)?;
    Ok(vec![text(result)])
}

fn commit_and_pr(root: &std::path::Path, paths: &[std::path::PathBuf], desc: &str) -> Result<String, String> {
    use std::process::Command;

    // Stage the paths.
    let mut add = Command::new("git");
    add.current_dir(root).arg("add");
    for p in paths { add.arg(p); }
    let out = add.output().map_err(|e| e.to_string())?;
    if !out.status.success() {
        return Err(format!("git add failed: {}", String::from_utf8_lossy(&out.stderr)));
    }

    // Check what was staged.
    let diff = Command::new("git")
        .current_dir(root)
        .args(["diff", "--cached", "--name-only"])
        .output().map_err(|e| e.to_string())?;
    let staged = String::from_utf8_lossy(&diff.stdout);
    if staged.trim().is_empty() {
        return Ok("Nothing new to submit — all models are already committed.".into());
    }

    // Commit.
    let msg = format!("feat(lint): {desc}");
    let commit = Command::new("git")
        .current_dir(root)
        .args(["commit", "-m", &msg])
        .output().map_err(|e| e.to_string())?;
    if !commit.status.success() {
        return Err(format!("git commit failed: {}", String::from_utf8_lossy(&commit.stderr)));
    }

    // Push (best-effort; continue even if remote is not set).
    let push = Command::new("git")
        .current_dir(root)
        .args(["push", "origin", "HEAD"])
        .output();
    let pushed = push.map(|o| o.status.success()).unwrap_or(false);

    // Open a PR if gh is available.
    let pr_url = if pushed {
        let pr = Command::new("gh")
            .current_dir(root)
            .args([
                "pr", "create",
                "--title", &format!("feat(lint): {desc}"),
                "--body",
                "Adds newly trained language model(s) crawled from official docs.\n\n\
                 Every rule has a bad/good example sourced from the official linter docs; \
                 patterns were compiled with the lossless tree-pattern engine.\n\n\
                 Reviewers: load this branch and run `helpers lint` on a project of the \
                 trained language to verify 0 false positives.\n\n\
                 Generated by `lint_submit`.",
            ])
            .output()
            .ok();
        pr.and_then(|o| if o.status.success() {
            Some(String::from_utf8_lossy(&o.stdout).trim().to_string())
        } else {
            None
        })
    } else {
        None
    };

    let mut msg = format!("Committed.\nFiles:\n{staged}");
    if pushed {
        msg.push_str("Pushed to origin.\n");
    } else {
        msg.push_str("Could not push (no remote or no credentials) — push manually.\n");
    }
    if let Some(url) = pr_url {
        msg.push_str(&format!("PR: {url}\n"));
    } else if pushed {
        msg.push_str("(Install `gh` and authenticate to auto-open PRs.)\n");
    }
    Ok(msg)
}

/// Publish every current-`TRAIN_VERSION` TRAINED MODULE (distilled via
/// [`crate::lint_train::export_module`] — learned rules + reference corpus + provenance,
/// never documentation or reading memory) to the `lint-models` branch of `origin` — the
/// GitHub model registry [`crate::lint_train`] pulls from. Pure git plumbing (blobs → tree →
/// commit → push); the working tree is never touched. The branch holds `index.json`
/// (`[{language, toolchain, train_version, sources, file}]`) beside the module files, exactly
/// the shape `registry_fetch` reads over raw.githubusercontent.com.
fn publish_models(repo_root: &std::path::Path) -> Result<String, String> {
    use std::process::Command;
    let git = |args: &[&str]| -> Result<String, String> {
        let out = Command::new("git").current_dir(repo_root).args(args).output()
            .map_err(|e| format!("lint_submit: git: {e}"))?;
        if !out.status.success() {
            return Err(format!("lint_submit: git {}: {}", args.first().unwrap_or(&""), String::from_utf8_lossy(&out.stderr)));
        }
        Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
    };

    // Publish each current AI MODULE file exactly as it runs — the compiled artifact plus
    // its provenance timestamp, never documentation in any form. Stale modules are skipped
    // (their provenance header names an older TRAIN_VERSION).
    let dir = crate::lint_train::model_dir_pub();
    let mut published: Vec<(String, String, String, String, String)> = Vec::new(); // (lang, toolchain, sources_fp, blob, sha256)
    for entry in std::fs::read_dir(&dir).map_err(|e| format!("lint_submit: {e}"))?.flatten() {
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else { continue };
        let Some(lang) = name.strip_suffix(".module.json") else { continue };
        // Provenance serializes first: probe the header instead of parsing the engines.
        let Ok(raw) = std::fs::read_to_string(&path) else { continue };
        let head = raw.get(..512).unwrap_or(&raw);
        if !head.contains(&format!("\"train_version\":\"{}\"", crate::lint_train::train_version())) {
            continue;
        }
        let field = |key: &str| -> String {
            head.split(&format!("\"{key}\":\""))
                .nth(1)
                .and_then(|r| r.split('"').next())
                .unwrap_or("")
                .to_string()
        };
        let blob = git(&["hash-object", "-w", path.to_str().unwrap_or_default()])?;
        let sha256 = crate::lint_sign::sha256_hex(raw.as_bytes());
        published.push((lang.to_string(), field("version"), field("sources_fp"), blob, sha256));
    }
    if published.is_empty() {
        return Err("lint_submit: no current AI modules in the machine cache — run `lint_config action=train` first".into());
    }
    published.sort();

    // index.json + one file per module, named for humans and keyed by the index for machines.
    let file_of = |lang: &str, toolchain: &str| -> String {
        let v: String = toolchain.chars().map(|c| if c.is_ascii_alphanumeric() || c == '.' { c } else { '-' }).collect();
        format!("{lang}@{}.module.json", if v.is_empty() { "any".to_string() } else { v })
    };
    let mut index: Vec<serde_json::Value> = published.iter().map(|(lang, toolchain, sources_fp, _, sha256)| json!({
        "language": lang,
        "toolchain": toolchain,
        "train_version": crate::lint_train::train_version(),
        "sources": sources_fp,
        "sha256": sha256,
        "module": file_of(lang, toolchain),
    })).collect();
    // BACKDATED VERSIONS KEEP WORKING: merge the remote index and carry forward every module
    // this publish does not supersede (other toolchains, other training versions) — their
    // blobs ride along from the fetched branch tip, so a machine on an older toolchain still
    // pulls its module.
    let mut carried: Vec<(String, String)> = Vec::new(); // (file, blob)
    let fetched = git(&["fetch", "origin", "lint-models"]).is_ok();
    if fetched {
        // Supersession keys on WHAT the module is for — language @ toolchain @ sources @
        // train_version — never on file names (the catalog-era registry used different names,
        // and carrying those forward would keep megabytes of superseded state alive).
        let key = |e: &serde_json::Value| -> String {
            format!(
                "{}@{}@{}@{}",
                e["language"].as_str().unwrap_or(""),
                e["toolchain"].as_str().unwrap_or(""),
                e["sources"].as_str().unwrap_or(""),
                e["train_version"].as_str().unwrap_or("")
            )
        };
        let ours: std::collections::HashSet<String> = index.iter().map(key).collect();
        let old_tree = git(&["ls-tree", "-r", "FETCH_HEAD"]).unwrap_or_default();
        let old_blobs: std::collections::HashMap<String, String> = old_tree
            .lines()
            .filter_map(|l| {
                let (meta, name) = l.split_once('\t')?;
                let sha = meta.split_whitespace().nth(2)?;
                Some((name.to_string(), sha.to_string()))
            })
            .collect();
        if let Ok(old_index_json) = git(&["show", "FETCH_HEAD:index.json"]) {
            if let Ok(old_index) = serde_json::from_str::<Vec<serde_json::Value>>(&old_index_json) {
                for entry in old_index {
                    let Some(file) = entry["module"].as_str().or_else(|| entry["file"].as_str()) else { continue };
                    if ours.contains(&key(&entry)) || !old_blobs.contains_key(file) {
                        continue;
                    }
                    carried.push((file.to_string(), old_blobs[file].clone()));
                    index.push(entry);
                }
            }
        }
    }
    let index_path = dir.join("index.json");
    let index_pretty = serde_json::to_string_pretty(&index).unwrap_or_default();
    std::fs::write(&index_path, &index_pretty).map_err(|e| format!("lint_submit: {e}"))?;
    let index_blob = git(&["hash-object", "-w", index_path.to_str().unwrap_or_default()])?;

    // The consumed branch is only real when the registry key signed exactly these index
    // bytes — consumers refuse anything else, so an attacker "publishing" here is inert.
    let signature = crate::lint_sign::sign(index_pretty.as_bytes())?;
    let sig_path = dir.join("index.sig.staging");
    std::fs::write(&sig_path, &signature).map_err(|e| format!("lint_submit: {e}"))?;
    let sig_blob = git(&["hash-object", "-w", sig_path.to_str().unwrap_or_default()])?;
    let _ = std::fs::remove_file(&sig_path);

    let mut tree_lines: Vec<String> = published
        .iter()
        .map(|(lang, toolchain, _, blob, _)| format!("100644 blob {blob}\t{}", file_of(lang, toolchain)))
        .collect();
    for (file, blob) in &carried {
        tree_lines.push(format!("100644 blob {blob}\t{file}"));
    }
    tree_lines.push(format!("100644 blob {index_blob}\tindex.json"));
    tree_lines.push(format!("100644 blob {sig_blob}\tindex.sig"));
    // One entry per path — a carried backdated module must never collide with a freshly
    // published file name (git rejects a tree with duplicate entries); published wins.
    let mut seen_paths = std::collections::HashSet::new();
    tree_lines.retain(|line| {
        line.rsplit('\t').next().map(|p| seen_paths.insert(p.to_string())).unwrap_or(false)
    });
    let mktree = Command::new("git")
        .current_dir(repo_root)
        .args(["mktree"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("lint_submit: git mktree: {e}"))?;
    use std::io::Write as _;
    mktree.stdin.as_ref().ok_or("lint_submit: mktree stdin")?
        .write_all(format!("{}\n", tree_lines.join("\n")).as_bytes())
        .map_err(|e| format!("lint_submit: {e}"))?;
    let out = mktree.wait_with_output().map_err(|e| format!("lint_submit: {e}"))?;
    if !out.status.success() {
        return Err(format!("lint_submit: git mktree: {}", String::from_utf8_lossy(&out.stderr)));
    }
    let tree = String::from_utf8_lossy(&out.stdout).trim().to_string();

    let msg = format!(
        "lint modules: {} language(s) @ {}",
        published.len(),
        crate::lint_train::train_version()
    );
    let commit = if fetched {
        git(&["commit-tree", &tree, "-p", "FETCH_HEAD", "-m", &msg])?
    } else {
        git(&["commit-tree", &tree, "-m", &msg])?
    };
    git(&["push", "--force", "origin", &format!("{commit}:refs/heads/lint-models")])?;

    let langs: Vec<&str> = published.iter().map(|(l, _, _, _, _)| l.as_str()).collect();
    let fingerprint = crate::lint_sign::machine_fingerprint()?;
    Ok(format!(
        "Published {} AI module(s) to origin/lint-models: {}.\n\
         Index signed by registry key {}… — consumers verify the signature and each module's \
         SHA-256 before loading; anything else falls through to reading the docs. A module is \
         the compiled runnable artifact + provenance timestamp — never documentation.",
        published.len(),
        langs.join(", "),
        &fingerprint[..16]
    ))
}

/// MCP schema for the `lint_submit` tool.
pub fn schema_submit() -> Value {
    json!({
        "name": "lint_submit",
        "description": "Commit corpus/sources registry changes, push, and open a GitHub PR so others learn the same docs. Trained models stay in the machine-global cache (~/.cache/helpers/lint-models), never in the repo. \
                        Pass include_feedback=true to also share this project's lint feedback log (.helpers/lint-feedback.jsonl) — the false-positive and missed flags recorded by lint_flag — so the shared rules can improve. Off by default since feedback may reference private paths.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "description": "Short description for the commit message and PR title. Default: 'Add trained language models from official docs'."
                },
                "include_feedback": {
                    "type": "boolean",
                    "description": "Opt-in: also stage and share .helpers/lint-feedback.jsonl (lint_flag feedback). Default false."
                },
                "identity": {
                    "type": "boolean",
                    "description": "Print this machine's signing identity (public key fingerprint). Default false."
                },
                "models": {
                    "type": "boolean",
                    "description": "Publish this machine's learned catalogs to the GitHub model registry (the lint-models branch of origin) so other machines download instead of re-crawling. Default false."
                }
            },
            "required": []
        }
    })
}

// ── lint_rule ─────────────────────────────────────────────────────────────────

/// Add a single custom rule to the project linter by providing a bad/good code example pair.
///
/// Writes (or appends) to `.helpers/lint-rules/<language>.md` in the project root, using the
/// same markdown format as `corpus/cs-principles.md`. The linter picks the rule up automatically
/// on the next run (the compiled pattern stamp is invalidated so a retrain is triggered).
pub fn run_rule(args: &Value) -> ToolResult {
    let lang = args["language"].as_str().ok_or("lint_rule: `language` is required")?;
    let id = args["id"].as_str().ok_or("lint_rule: `id` is required")?;
    let bad = args["bad"].as_str().ok_or("lint_rule: `bad` is required")?;
    let good = args["good"].as_str().unwrap_or("");
    let description = args["description"].as_str().unwrap_or(id);
    let severity = args["severity"].as_str().unwrap_or("medium");
    let root = args["root"]
        .as_str()
        .map(std::path::PathBuf::from)
        .unwrap_or_else(crate::git::workspace_root);

    let rules_dir = root.join(".helpers/lint-rules");
    std::fs::create_dir_all(&rules_dir).map_err(|e| format!("lint_rule: {e}"))?;

    let file = rules_dir.join(format!("{lang}.md"));
    let mut content = std::fs::read_to_string(&file).unwrap_or_default();

    // Append the rule in corpus markdown format: heading, description, fenced bad/good pair.
    let block = format!(
        "\n## {id} [{severity}]\n\n{description}\n\n\
         ```{lang}:bad\n{bad}\n```\n\n\
         ```{lang}:good\n{good}\n```\n"
    );
    content.push_str(&block);
    std::fs::write(&file, &content).map_err(|e| format!("lint_rule: {e}"))?;

    // Invalidate the compiled pattern stamp so the next `lint` run retrains this language.
    crate::lint_train::invalidate_module(lang);

    Ok(vec![text(format!(
        "Rule `{id}` added to `.helpers/lint-rules/{lang}.md`.\n\
         Severity: {severity}.\n\
         Description: {description}\n\n\
         The linter will retrain on the next `lint` run and apply this rule automatically."
    ))])
}

/// MCP schema for the `lint_rule` tool.
pub fn schema_rule() -> Value {
    json!({
        "name": "lint_rule",
        "description": "Add a custom lint rule to the project by providing a bad/good code example pair. \
                        Writes to .helpers/lint-rules/<language>.md (created if needed) in the project root. \
                        No other setup required — the linter picks it up automatically on the next run. \
                        Use this to encode project-specific conventions, security rules, style preferences, \
                        or any pattern you want enforced consistently across the codebase.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "language":    { "type": "string", "description": "Language the rule applies to (e.g. python, rust, javascript, go)." },
                "id":          { "type": "string", "description": "Unique rule id in snake_case (e.g. no_bare_eval, require_logging)." },
                "bad":         { "type": "string", "description": "Code snippet that violates the rule — the pattern to detect." },
                "good":        { "type": "string", "description": "The correct form. Omit if the rule is purely prohibitive with no fix." },
                "description": { "type": "string", "description": "Human-readable advice shown in lint output: WHY it's wrong and WHAT to do instead." },
                "severity":    { "type": "string", "enum": ["high", "medium", "low"], "description": "How serious the violation is. Default: medium." },
                "root":        { "type": "string", "description": "Project root. Defaults to the workspace root." }
            },
            "required": ["language", "id", "bad", "description"]
        }
    })
}

// ── lint_config ───────────────────────────────────────────────────────────────

/// Read or write the project's lint preferences in `.helpers/lint.json`.
pub fn run_config(args: &Value) -> ToolResult {
    let action = args["action"].as_str().unwrap_or("get");
    let root = args["root"]
        .as_str()
        .map(std::path::PathBuf::from)
        .unwrap_or_else(crate::git::workspace_root);

    let cfg_path = root.join(".helpers/lint.json");
    let mut cfg: serde_json::Value = std::fs::read_to_string(&cfg_path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_else(|| json!({"ignore_rules": [], "severity_overrides": {}}));

    match action {
        "get" => Ok(vec![text(format!(
            "Lint config ({})\n{}",
            cfg_path.display(),
            serde_json::to_string_pretty(&cfg).unwrap_or_default()
        ))]),
        "ignore" => {
            let rule = args["rule"].as_str()
                .ok_or("lint_config: `rule` required for action=ignore")?;
            let list = cfg["ignore_rules"].as_array_mut()
                .ok_or("lint_config: malformed ignore_rules")?;
            if !list.iter().any(|v| v.as_str() == Some(rule)) {
                list.push(json!(rule));
            }
            save_config(&cfg_path, &cfg)?;
            Ok(vec![text(format!("Rule `{rule}` suppressed. It will not appear in lint output."))])
        }
        "unignore" => {
            let rule = args["rule"].as_str()
                .ok_or("lint_config: `rule` required for action=unignore")?;
            if let Some(list) = cfg["ignore_rules"].as_array_mut() {
                list.retain(|v| v.as_str() != Some(rule));
            }
            save_config(&cfg_path, &cfg)?;
            Ok(vec![text(format!("Rule `{rule}` re-enabled."))])
        }
        "severity" => {
            let rule = args["rule"].as_str()
                .ok_or("lint_config: `rule` required for action=severity")?;
            let sev = args["severity"].as_str()
                .ok_or("lint_config: `severity` required for action=severity")?;
            cfg["severity_overrides"][rule] = json!(sev);
            save_config(&cfg_path, &cfg)?;
            Ok(vec![text(format!("Rule `{rule}` severity overridden to `{sev}`."))])
        }
        "set_languages" => {
            let langs = args["languages"].as_array()
                .ok_or("lint_config: `languages` array required")?;
            cfg["languages"] = json!(langs);
            save_config(&cfg_path, &cfg)?;
            let names: Vec<&str> = langs.iter().filter_map(|v| v.as_str()).collect();
            Ok(vec![text(format!("Language filter set to: {}", names.join(", ")))])
        }
        // Batch training (LINTER.md, "Every registered language trains in one batch"): run the
        // pipeline for every language the registry names (plus every discovered one) in
        // parallel. Models are machine-global, so after one batch every repo on the machine
        // lints every known language instantly.
        "train" => {
            let started = std::time::Instant::now();
            // The ONE setup verb: network acquisition is allowed here and nowhere else.
            crate::lint_train::allow_network_setup();
            let data = crate::tools::lint::data_root_pub();
            let mut langs = crate::lint_train::registered_languages(&data);
            // The current project's own languages train too — an unknown language is
            // discovered by web search here, never during a lint run.
            for lang in crate::tools::lint::project_languages(&root) {
                if !langs.contains(&lang) {
                    langs.push(lang);
                }
            }
            langs.sort();
            if langs.is_empty() {
                return Err("lint_config: nothing to train — no languages registered and none in the project".into());
            }
            let (report, models) = crate::lint_train::ensure_models(
                &langs,
                &data,
                &root,
                &std::collections::BTreeMap::new(),
            );
            let mut lines: Vec<String> = Vec::new();
            for lang in &langs {
                let state = match models.get(lang) {
                    Some(m) if !report.unlearned.contains(lang) => {
                        format!("{} rule(s)", m.rules.rule_count())
                    }
                    _ if !crate::lint_train::has_docs_source(&data, lang) => {
                        "needs a docs URL — `lint_config action=add_source`".to_string()
                    }
                    _ => "docs not learned".to_string(),
                };
                lines.push(format!("  {lang}: {state}"));
            }
            let mut body = format!(
                "Trained {} language(s) in {:.1}s — models are machine-global, every repo is live:\n{}\n",
                langs.len(),
                started.elapsed().as_secs_f64(),
                lines.join("\n")
            );
            if !report.pulled.is_empty() {
                body.push_str(&format!(
                    "\nDownloaded from the model registry: {}.\n",
                    report.pulled.join(", ")
                ));
            }
            if report.net_down {
                body.push_str(
                    "\nThe network was unreachable for some of it — setup needs internet. \
                     Reconnect and rerun `lint_config action=train` to finish.\n",
                );
            }
            Ok(vec![text(body)])
        }
        // Register a documentation source (LINTER.md, "Online to set up, offline to run"):
        // a data write into the discovery cache — overwrites a failed discovery's negative
        // marker and drops the language's model stamp so the next train/lint learns it.
        // Offline-safe; trains nothing by itself (`action=train` is the training verb).
        "add_source" => {
            let lang_arg = args["lang"].as_str()
                .ok_or("lint_config: `lang` required for action=add_source")?
                .to_lowercase();
            // Aliases resolve exactly like rule-file stems and fence hints (ledger #16).
            let lang = crate::util::file_lang(&lang_arg).unwrap_or(&lang_arg).to_string();
            let url = args["url"].as_str()
                .ok_or("lint_config: `url` required for action=add_source")?;
            crate::lint_docs::add_docs_source(&lang, url);
            crate::lint_train::invalidate_module(&lang);
            Ok(vec![text(format!(
                "Registered {url} as `{lang}`'s documentation source. Now run \
                 `lint_config action=train` (needs internet) — after that, linting `{lang}` \
                 works offline on every repo on this machine."
            ))])
        }
        _ => Err(format!(
            "lint_config: unknown action `{action}`. Valid: get | ignore | unignore | severity | set_languages | add_source | train"
        )),
    }
}

fn save_config(path: &std::path::Path, cfg: &serde_json::Value) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("lint_config: {e}"))?;
    }
    std::fs::write(path, serde_json::to_string_pretty(cfg).unwrap_or_default())
        .map_err(|e| format!("lint_config: {e}"))
}

/// MCP schema for the `lint_config` tool.
pub fn schema_config() -> Value {
    json!({
        "name": "lint_config",
        "description": "Read or write the project's lint preferences (.helpers/lint.json). \
                        Suppress noisy rules, change severities, restrict which languages are reviewed, \
                        add a language's official docs source (action=add_source), or train every \
                        registered language (action=train). Online to set up, offline to run. \
                        Changes take effect on the next `lint` run.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["get", "ignore", "unignore", "severity", "set_languages", "add_source", "train"],
                    "description": "get=show config | ignore=suppress a rule | unignore=re-enable | severity=change level | set_languages=restrict languages | add_source=register a language's official docs URL (offline-safe; trains nothing) | train=train every registered language (needs internet for anything missing) — online to set up, offline to run"
                },
                "rule":      { "type": "string", "description": "Rule id (for ignore/unignore/severity)." },
                "severity":  { "type": "string", "enum": ["high","medium","low"], "description": "New severity (for action=severity)." },
                "languages": { "type": "array",  "items": {"type": "string"}, "description": "Languages to lint (for set_languages). Pass [] to clear the filter." },
                "lang":      { "type": "string", "description": "Language the docs cover (for action=add_source). Extension aliases resolve (js ⇒ javascript)." },
                "url":       { "type": "string", "description": "The language's official documentation URL (for action=add_source)." },
                "root":      { "type": "string", "description": "Project root. Defaults to the workspace root." }
            },
            "required": ["action"]
        }
    })
}
