//! MCP tools for sharing and tuning the linter's learned knowledge.
//!
//! Languages self-train: the lint run itself crawls official docs for any language it sees and
//! caches the model (near-instant reuse after first setup). These tools cover the human loop:
//!
//! * `lint_submit` — commit trained models + corpus, push, and open a GitHub PR (share knowledge).
//! * `lint_rule`   — author/promote a project rule (including feedback drafts) into `.helpers/lint-rules/`.
//! * `lint_config` — per-project ignores/severity overrides (rarely needed; feedback flags manage this).

use serde_json::{json, Value};

use crate::proto::{text, ToolResult};

// ── lint_submit ───────────────────────────────────────────────────────────────

/// Commit newly-trained models + corpus changes and open a GitHub PR so others get them.
pub fn run_submit(args: &Value) -> ToolResult {
    let desc = args["description"]
        .as_str()
        .unwrap_or("Add trained language models from official docs");
    let data_root = crate::tools::lint::data_root_pub();
    let repo_root = crate::git::workspace_root();

    let mut paths: Vec<std::path::PathBuf> = ["lint-models", "lint-index/sources.json", "corpus"]
        .iter()
        .map(|p| data_root.join(p))
        .filter(|p| p.exists())
        .collect();

    // Opt-in: also share the project's lint feedback log so false-positive/missed flags can
    // improve the shared rules. Off by default because feedback may reference private file paths.
    if args["include_feedback"].as_bool().unwrap_or(false) {
        let fb = crate::lint_feedback::feedback_path(&repo_root);
        if fb.exists() {
            paths.push(fb);
        }
    }

    if paths.is_empty() {
        return Err("lint_submit: nothing to submit — no lint-models, sources, corpus, or feedback found".into());
    }

    let result = commit_and_pr(&repo_root, &paths, desc)?;
    Ok(vec![text(result)])
}

fn commit_and_pr(root: &std::path::Path, paths: &[std::path::PathBuf], desc: &str) -> Result<String, String> {
    use std::process::Command;

    // Stage the paths.
    let mut add = Command::new("git");
    add.current_dir(root).arg("add");
    for p in paths { add.arg(p); }
    let out = add.output().map_err(|e| e.to_string())?;
    if !out.status.success() {
        return Err(format!("git add failed: {}", String::from_utf8_lossy(&out.stderr)));
    }

    // Check what was staged.
    let diff = Command::new("git")
        .current_dir(root)
        .args(["diff", "--cached", "--name-only"])
        .output().map_err(|e| e.to_string())?;
    let staged = String::from_utf8_lossy(&diff.stdout);
    if staged.trim().is_empty() {
        return Ok("Nothing new to submit — all models are already committed.".into());
    }

    // Commit.
    let msg = format!("feat(lint): {desc}");
    let commit = Command::new("git")
        .current_dir(root)
        .args(["commit", "-m", &msg])
        .output().map_err(|e| e.to_string())?;
    if !commit.status.success() {
        return Err(format!("git commit failed: {}", String::from_utf8_lossy(&commit.stderr)));
    }

    // Push (best-effort; continue even if remote is not set).
    let push = Command::new("git")
        .current_dir(root)
        .args(["push", "origin", "HEAD"])
        .output();
    let pushed = push.map(|o| o.status.success()).unwrap_or(false);

    // Open a PR if gh is available.
    let pr_url = if pushed {
        let pr = Command::new("gh")
            .current_dir(root)
            .args([
                "pr", "create",
                "--title", &format!("feat(lint): {desc}"),
                "--body",
                "Adds newly trained language model(s) crawled from official docs.\n\n\
                 Every rule has a bad/good example sourced from the official linter docs; \
                 patterns were compiled with the lossless tree-pattern engine.\n\n\
                 Reviewers: load this branch and run `helpers lint` on a project of the \
                 trained language to verify 0 false positives.\n\n\
                 Generated by `lint_submit`.",
            ])
            .output()
            .ok();
        pr.and_then(|o| if o.status.success() {
            Some(String::from_utf8_lossy(&o.stdout).trim().to_string())
        } else {
            None
        })
    } else {
        None
    };

    let mut msg = format!("Committed.\nFiles:\n{staged}");
    if pushed {
        msg.push_str("Pushed to origin.\n");
    } else {
        msg.push_str("Could not push (no remote or no credentials) — push manually.\n");
    }
    if let Some(url) = pr_url {
        msg.push_str(&format!("PR: {url}\n"));
    } else if pushed {
        msg.push_str("(Install `gh` and authenticate to auto-open PRs.)\n");
    }
    Ok(msg)
}

/// MCP schema for the `lint_submit` tool.
pub fn schema_submit() -> Value {
    json!({
        "name": "lint_submit",
        "description": "Commit newly-trained lint-models and corpus/sources changes, push, and open a GitHub PR so others get the trained language models on git pull. Run lint_learn first to train a language. \
                        Pass include_feedback=true to also share this project's lint feedback log (.helpers/lint-feedback.jsonl) — the false-positive and missed flags recorded by lint_flag — so the shared rules can improve. Off by default since feedback may reference private paths.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "description": "Short description for the commit message and PR title. Default: 'Add trained language models from official docs'."
                },
                "include_feedback": {
                    "type": "boolean",
                    "description": "Opt-in: also stage and share .helpers/lint-feedback.jsonl (lint_flag feedback). Default false."
                }
            },
            "required": []
        }
    })
}

// ── lint_rule ─────────────────────────────────────────────────────────────────

/// Add a single custom rule to the project linter by providing a bad/good code example pair.
///
/// Writes (or appends) to `.helpers/lint-rules/<language>.md` in the project root, using the
/// same markdown format as `corpus/cs-principles.md`. The linter picks the rule up automatically
/// on the next run (the compiled pattern stamp is invalidated so a retrain is triggered).
pub fn run_rule(args: &Value) -> ToolResult {
    let lang = args["language"].as_str().ok_or("lint_rule: `language` is required")?;
    let id = args["id"].as_str().ok_or("lint_rule: `id` is required")?;
    let bad = args["bad"].as_str().ok_or("lint_rule: `bad` is required")?;
    let good = args["good"].as_str().unwrap_or("");
    let description = args["description"].as_str().unwrap_or(id);
    let severity = args["severity"].as_str().unwrap_or("medium");
    let root = args["root"]
        .as_str()
        .map(std::path::PathBuf::from)
        .unwrap_or_else(crate::git::workspace_root);

    let rules_dir = root.join(".helpers/lint-rules");
    std::fs::create_dir_all(&rules_dir).map_err(|e| format!("lint_rule: {e}"))?;

    let file = rules_dir.join(format!("{lang}.md"));
    let mut content = std::fs::read_to_string(&file).unwrap_or_default();

    // Append the rule in corpus markdown format: heading, description, fenced bad/good pair.
    let block = format!(
        "\n## {id} [{severity}]\n\n{description}\n\n\
         ```{lang}:bad\n{bad}\n```\n\n\
         ```{lang}:good\n{good}\n```\n"
    );
    content.push_str(&block);
    std::fs::write(&file, &content).map_err(|e| format!("lint_rule: {e}"))?;

    // Invalidate the compiled pattern stamp so the next `lint` run retrains this language.
    let _ = std::fs::remove_file(crate::lint_train::stamp_path_pub(lang));

    Ok(vec![text(format!(
        "Rule `{id}` added to `.helpers/lint-rules/{lang}.md`.\n\
         Severity: {severity}.\n\
         Description: {description}\n\n\
         The linter will retrain on the next `lint` run and apply this rule automatically."
    ))])
}

/// MCP schema for the `lint_rule` tool.
pub fn schema_rule() -> Value {
    json!({
        "name": "lint_rule",
        "description": "Add a custom lint rule to the project by providing a bad/good code example pair. \
                        Writes to .helpers/lint-rules/<language>.md (created if needed) in the project root. \
                        No other setup required — the linter picks it up automatically on the next run. \
                        Use this to encode project-specific conventions, security rules, style preferences, \
                        or any pattern you want enforced consistently across the codebase.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "language":    { "type": "string", "description": "Language the rule applies to (e.g. python, rust, javascript, go)." },
                "id":          { "type": "string", "description": "Unique rule id in snake_case (e.g. no_bare_eval, require_logging)." },
                "bad":         { "type": "string", "description": "Code snippet that violates the rule — the pattern to detect." },
                "good":        { "type": "string", "description": "The correct form. Omit if the rule is purely prohibitive with no fix." },
                "description": { "type": "string", "description": "Human-readable advice shown in lint output: WHY it's wrong and WHAT to do instead." },
                "severity":    { "type": "string", "enum": ["high", "medium", "low"], "description": "How serious the violation is. Default: medium." },
                "root":        { "type": "string", "description": "Project root. Defaults to the workspace root." }
            },
            "required": ["language", "id", "bad", "description"]
        }
    })
}

// ── lint_config ───────────────────────────────────────────────────────────────

/// Read or write the project's lint preferences in `.helpers/lint.json`.
pub fn run_config(args: &Value) -> ToolResult {
    let action = args["action"].as_str().unwrap_or("get");
    let root = args["root"]
        .as_str()
        .map(std::path::PathBuf::from)
        .unwrap_or_else(crate::git::workspace_root);

    let cfg_path = root.join(".helpers/lint.json");
    let mut cfg: serde_json::Value = std::fs::read_to_string(&cfg_path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_else(|| json!({"ignore_rules": [], "severity_overrides": {}}));

    match action {
        "get" => Ok(vec![text(format!(
            "Lint config ({})\n{}",
            cfg_path.display(),
            serde_json::to_string_pretty(&cfg).unwrap_or_default()
        ))]),
        "ignore" => {
            let rule = args["rule"].as_str()
                .ok_or("lint_config: `rule` required for action=ignore")?;
            let list = cfg["ignore_rules"].as_array_mut()
                .ok_or("lint_config: malformed ignore_rules")?;
            if !list.iter().any(|v| v.as_str() == Some(rule)) {
                list.push(json!(rule));
            }
            save_config(&cfg_path, &cfg)?;
            Ok(vec![text(format!("Rule `{rule}` suppressed. It will not appear in lint output."))])
        }
        "unignore" => {
            let rule = args["rule"].as_str()
                .ok_or("lint_config: `rule` required for action=unignore")?;
            if let Some(list) = cfg["ignore_rules"].as_array_mut() {
                list.retain(|v| v.as_str() != Some(rule));
            }
            save_config(&cfg_path, &cfg)?;
            Ok(vec![text(format!("Rule `{rule}` re-enabled."))])
        }
        "severity" => {
            let rule = args["rule"].as_str()
                .ok_or("lint_config: `rule` required for action=severity")?;
            let sev = args["severity"].as_str()
                .ok_or("lint_config: `severity` required for action=severity")?;
            cfg["severity_overrides"][rule] = json!(sev);
            save_config(&cfg_path, &cfg)?;
            Ok(vec![text(format!("Rule `{rule}` severity overridden to `{sev}`."))])
        }
        "set_languages" => {
            let langs = args["languages"].as_array()
                .ok_or("lint_config: `languages` array required")?;
            cfg["languages"] = json!(langs);
            save_config(&cfg_path, &cfg)?;
            let names: Vec<&str> = langs.iter().filter_map(|v| v.as_str()).collect();
            Ok(vec![text(format!("Language filter set to: {}", names.join(", ")))])
        }
        _ => Err(format!(
            "lint_config: unknown action `{action}`. Valid: get | ignore | unignore | severity | set_languages"
        )),
    }
}

fn save_config(path: &std::path::Path, cfg: &serde_json::Value) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("lint_config: {e}"))?;
    }
    std::fs::write(path, serde_json::to_string_pretty(cfg).unwrap_or_default())
        .map_err(|e| format!("lint_config: {e}"))
}

/// MCP schema for the `lint_config` tool.
pub fn schema_config() -> Value {
    json!({
        "name": "lint_config",
        "description": "Read or write the project's lint preferences (.helpers/lint.json). \
                        Suppress noisy rules, change severities, or restrict which languages are reviewed — \
                        without touching any source file. Changes take effect on the next `lint` run.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["get", "ignore", "unignore", "severity", "set_languages"],
                    "description": "get=show config | ignore=suppress a rule | unignore=re-enable | severity=change level | set_languages=restrict languages"
                },
                "rule":      { "type": "string", "description": "Rule id (for ignore/unignore/severity)." },
                "severity":  { "type": "string", "enum": ["high","medium","low"], "description": "New severity (for action=severity)." },
                "languages": { "type": "array",  "items": {"type": "string"}, "description": "Languages to lint (for set_languages). Pass [] to clear the filter." },
                "root":      { "type": "string", "description": "Project root. Defaults to the workspace root." }
            },
            "required": ["action"]
        }
    })
}
